version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1020
        - -ST1021
        - -QF1003
        - -QF1012
        - -S1001
        - -S1024
        - -S1034

issues:
  max-same-issues: 3
  max-issues-per-linter: 50
