package io.github.mystisql.jdbc;

import java.sql.*;

/**
 * MystiSql JDBC Statement implementation.
 */
public class MystiSqlStatement implements Statement {
    
    private final MystiSqlConnection connection;
    private ResultSet currentResultSet;
    private int updateCount = -1;
    private int queryTimeout = 0;
    private boolean closed = false;
    
    public MystiSqlStatement(MystiSqlConnection connection) {
        this.connection = connection;
    }
    
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkClosed();
        // TODO: Implement HTTP call to Gateway
        throw new SQLException("Not implemented yet");
    }
    
    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkClosed();
        // TODO: Implement HTTP call to Gateway
        throw new SQLException("Not implemented yet");
    }
    
    @Override
    public void close() throws SQLException {
        closed = true;
        if (currentResultSet != null) {
            currentResultSet.close();
        }
    }
    
    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }
    
    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkClosed();
        this.queryTimeout = seconds;
    }
    
    @Override
    public int getQueryTimeout() throws SQLException {
        checkClosed();
        return queryTimeout;
    }
    
    @Override
    public Connection getConnection() throws SQLException {
        checkClosed();
        return connection;
    }
    
    @Override
    public ResultSet getResultSet() throws SQLException {
        checkClosed();
        return currentResultSet;
    }
    
    @Override
    public int getUpdateCount() throws SQLException {
        checkClosed();
        return updateCount;
    }
    
    private void checkClosed() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed");
        }
    }
    
    // Placeholder implementations for remaining methods
    @Override public int getMaxFieldSize() throws SQLException { return 0; }
    @Override public void setMaxFieldSize(int max) throws SQLException { }
    @Override public int getMaxRows() throws SQLException { return 0; }
    @Override public void setMaxRows(int max) throws SQLException { }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { }
    @Override public void cancel() throws SQLException { }
    @Override public SQLWarning getWarnings() throws SQLException { return null; }
    @Override public void clearWarnings() throws SQLException { }
    @Override public void setCursorName(String name) throws SQLException { }
    @Override public boolean execute(String sql) throws SQLException { throw new SQLException("Not implemented yet"); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { throw new SQLException("Not implemented yet"); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public void addBatch(String sql) throws SQLException { throw new SQLFeatureNotSupportedException("Batch operations not supported in Phase 2.5"); }
    @Override public void clearBatch() throws SQLException { }
    @Override public int[] executeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public long[] executeLargeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public long executeLargeUpdate(String sql) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public long getLargeUpdateCount() throws SQLException { return updateCount; }
    @Override public void setLargeMaxRows(long max) throws SQLException { }
    @Override public long getLargeMaxRows() throws SQLException { return 0; }
    @Override public boolean isPoolable() throws SQLException { return false; }
    @Override public void setPoolable(boolean poolable) throws SQLException { }
    @Override public void closeOnCompletion() throws SQLException { }
    @Override public boolean isCloseOnCompletion() throws SQLException { return false; }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return false; }
}
